/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoccao_javet_interop_NodeNative */

#ifndef _Included_com_caoccao_javet_interop_NodeNative
#define _Included_com_caoccao_javet_interop_NodeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caoccao_javet_interop_NodeNative
 * Method:    await
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caoccao_javet_interop_NodeNative_await
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_caoccao_javet_interop_NodeNative
 * Method:    isPurgeEventLoopBeforeClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caoccao_javet_interop_NodeNative_isPurgeEventLoopBeforeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_caoccao_javet_interop_NodeNative
 * Method:    setPurgeEventLoopBeforeClose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_caoccao_javet_interop_NodeNative_setPurgeEventLoopBeforeClose
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
