/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoccao_javet_interop_NodeNative */

#ifndef _Included_com_caoccao_javet_interop_NodeNative
#define _Included_com_caoccao_javet_interop_NodeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caoccao_javet_interop_NodeNative
 * Method:    await
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caoccao_javet_interop_NodeNative_await
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
